#pragma once
// Spec 21 §3.17 — Wigner function of an oscillator mode given as a density matrix in a Fock basis
// truncated at N_max:
//     W(α) = (2/π) Tr[ D†(α) ρ D(α) P ],   D(α) = exp(α a† − α* a),   P = exp(iπ a†a),
// i.e. the expectation of the parity operator displaced to α, so that a coherent state |β⟩ is the
// Gaussian (2/π) e^{−2|α−β|²} centred at α = +β. It is evaluated with the Laguerre expression
//     W(α) = (2/π) e^{−2|α|²} Σ_{m≥n} ρ_mn (−1)^n √(n!/m!) (2α*)^{m−n} L_n^{(m−n)}(4|α|²)  (+ c.c. for m < n)
// which follows from D(α) P D†(α) = D(2α) P and the Cahill–Glauber matrix elements of D.
// Phase-space axes: α = (x + i p)/√2, so d²α = dx dp / 2 and the vacuum is (2/π) e^{−(x² + p²)}.
#include "Core/Error.hpp"
#include "Numerics/Types.hpp"
#include <cstddef>
#include <vector>

namespace qlab::viz::math {

inline constexpr std::size_t kWignerMaxFock = 60;   // N_max ≤ 60 (spec 21 §3.17)
inline constexpr std::size_t kWignerMaxGrid = 201;  // grid ≤ 201 × 201

// W at one point. `rho` is (N+1)×(N+1), Hermitian, N ≤ 60. The normalised Laguerre functions
// l_n^{(k)}(x) = √(n!/(n+k)!) x^{k/2} e^{−x/2} L_n^{(k)}(x) are generated by their three-term
// recurrence, so no factorial or power ever overflows.
Result<double> wignerAt(const num::Matrix& rho, num::Complex alpha);

struct WignerOptions {
    double xMin = -5.0, xMax = 5.0, pMin = -5.0, pMax = 5.0;
    std::size_t nx = 101, ny = 101;
};

struct WignerGrid {
    WignerOptions axes;
    std::vector<double> values;   // row-major, values[iy·nx + ix] = W((x_ix + i p_iy)/√2); iy = 0 is pMin
    double minValue = 0.0, maxValue = 0.0;
    double integral = 0.0;        // ∫ W d²α over the grid (1 when the grid covers the state)
    double negativity = 0.0;      // ∫ |W| d²α − 1 (spec 21 §3.17), trapezoid rule on the grid
    double x(std::size_t ix) const;
    double p(std::size_t iy) const;
    double at(std::size_t ix, std::size_t iy) const { return values[iy * axes.nx + ix]; }
    // Symmetric colour range [−limit, +limit] of the diverging map: W = 0 is the neutral colour.
    double symmetricLimit() const;
};
Result<WignerGrid> wignerGrid(const num::Matrix& rho, const WignerOptions& options = {});

// Photon-number distribution P(n) = ρ_nn (the view plots it beside the heatmap).
std::vector<double> photonNumberDistribution(const num::Matrix& rho);

} // namespace qlab::viz::math
