#pragma once
// Spec 16 §1, T09 §1.1 — Pauli strings in binary symplectic form.
// Text form is written LEFT-TO-RIGHT FROM QUBIT 0 (position i is qubit i, spec 16 §1); this is the
// reverse of qsim::PauliString labels, which are most-significant qubit first. `toQsim` converts.
#include "QEC/Types.hpp"
#include "QSim/Types.hpp"
#include <cstdint>
#include <optional>
#include <span>
#include <string>
#include <string_view>
#include <vector>

namespace qlab::qec {

struct PauliString {
    // Letter of qubit q: I = (0,0), X = (1,0), Y = (1,1), Z = (0,1).
    std::vector<std::uint8_t> x, z;
    // The operator is i^phase · (tensor product of the Hermitian letters), phase ∈ {0,1,2,3}.
    // Y is a letter of its own, so "YY" has phase 0 (T09 §1.1 writes the same operator as
    // i²·XZ⊗XZ).
    std::int8_t phase = 0;
    std::uint32_t n = 0;

    static PauliString identity(std::uint32_t n);
    // One letter on one qubit of an n-qubit register; `letter` ∈ {I, X, Y, Z}.
    static PauliString single(std::uint32_t n, std::uint32_t qubit, char letter);
    // "XZZXI" with an optional leading "+", "-", "i", "+i" or "-i".
    static Result<PauliString> parse(std::string_view text);

    char letter(std::uint32_t q) const;
    void setLetter(std::uint32_t q, char c);       // c ∈ {I, X, Y, Z}; anything else is I
    std::string str(bool withPhase = false) const; // qubit 0 first
    std::uint32_t weight() const;
    std::vector<std::uint32_t> support() const;
    bool isIdentity() const; // every letter is I (any phase)
    bool isXType() const;    // letters in {I, X}
    bool isZType() const;    // letters in {I, Z}
    bool isHermitian() const { return (phase & 1) == 0; }
    bool sameLetters(const PauliString& o) const;
    // Symplectic form T09 (1.2): true when the two strings commute. Lengths must match.
    bool commutesWith(const PauliString& o) const;
    // Operator product this · o with the phase tracked (XY = iZ).
    PauliString operator*(const PauliString& o) const;
    bool operator==(const PauliString& o) const = default;

    // The same operator for a simulation backend (label most-significant qubit first).
    qsim::PauliString toQsim() const;
};

// s_j = 1 iff `error` anticommutes with generators[j] (T09 §2.3).
std::vector<std::uint8_t> syndromeOf(std::span<const PauliString> generators,
                                     const PauliString& error);

// Rank over F2 of the (x|z) rows (spec 16 §1 independence check).
std::uint32_t symplecticRank(std::span<const PauliString> rows);

// Solves Π_{j ∈ S} rows[j] ∝ target over F2 (letters only). Returns the subset S, or nothing when
// the target is outside the group generated by `rows`.
std::optional<std::vector<std::uint32_t>> solveProduct(std::span<const PauliString> rows,
                                                       const PauliString& target);

// True when the letters of `target` lie in the group generated by `rows`. `signOut`, when given,
// receives c ∈ {+1, −1} with Π_{j ∈ S} rows[j] = c · target, or 0 when the ratio is ±i (which
// cannot happen for commuting Hermitian rows and a Hermitian target).
bool inGroup(std::span<const PauliString> rows, const PauliString& target, int* signOut = nullptr);

} // namespace qlab::qec
