// VQE for H2 (STO-3G, 2-qubit parity-reduced Hamiltonian H = g0 I + g1 Z0 + g2 Z1 + g3 Z0Z1 + g4 X0X1 + g5 Y0Y1).
// Theory: T03 §9.1. Coefficients are loaded at run time from Assets/Programs/vqe/h2_sto3g.json (regenerated from an
// electronic-structure package, spec T03). The ansatz is the single-parameter UCC circuit; the estimator measures
// each Pauli term in its own basis (three programs generated by the runtime sweep; here: the ZZ/Z basis).
OPENQASM 3.0;
include "stdgates.inc";
pragma qlab.shots 8192
input float theta = -0.2263;
pragma qlab.sweep theta from -0.6 to 0.2 step 0.05
qubit[2] q;
bit[2] c;
output float energy_zz;
x q[0];
ry(theta) q[1];
cx q[1], q[0];
c = measure q;
